### ISSUE TITLE
Problems with the dark theme

### ISSUE THREAD

**Issue by ghost** [VivekThazhathattil/dekadico#16]
The app has a problem with the dark theme, I always use the dark theme on my phone and I have noticed that when I have the dark theme enabled the app closes by itself, it takes me out of the app, I have tried disabling the dark theme on my phone and I have been able to play, the same thing happens when I enable the dark theme from the app. Please fix that little bug, I always use my phone with the dark theme and would like to play with the dark theme enabled. Thanks in advance.

**Comment by VivekThazhathattil** [comment]
Thank you for reporting. The bug will be fixed in the next release.

**Comment by ghost** [comment]
Thank you for correcting the problem 👍
